spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.48.214:3306/expert_practice?serverTimezone=GMT%2b8
    username: root
    password: 123456
server:
  port: 9090

logging:
  level:
    root: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml